language: php

php:
    - 7.1

before_script:
    - ./composer.phar install --no-interaction --dev

script:
    - vendor/bin/phpunit tests/ --coverage-clover build/logs/clover.xml
    - vendor/bin/phpcs -w -p -s --standard=vendor/flyeralarm/php-code-validator/ruleset.xml src/ tests/
    
notifications:
    slack: karrlein:an1enYrAJKdow0DYS4sSvoGC
