sudo: true
dist: trusty
language: bash

jobs:
    stages:
        - build docker image
    include:
        - stage: build docker image
          script:
              - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
              - docker build -t $DOCKER_USERNAME/karrleincom:$TAG .
              - docker push $DOCKER_USERNAME/karrleincom
