version: '3'
services:
    web:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        image: karrlein.com/nginx
        ports:
            - "80:80"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        image: karrlein.com/php
